name: test-conda-env
channels:
- conda-forge
- nodefaults

dependencies:
- python=3
- numpy
- pocl
- mako
- pyopencl
- islpy
- sphinx-autodoc-typehints
- mpi4py
- jax
- openmpi  # Force using Open MPI since our pytest infrastructure needs it
