# FIXME: Should be in pytools
from typing import TypeVar, Iterable, Optional

T = TypeVar("T")

def memoize_method(f: T) -> T: ...
def is_single_valued(it: Iterable[T]) -> bool: ...

class UniqueNameGenerator:
    def __init__(self, existing_names: Optional[Iterable[str]], forced_prefix: str=""): ...
    def __call__(self, based_on: str = "") -> str: ...
